name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"

permissions:
  contents: write

concurrency:
  group: snake
  cancel-in-progress: false

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate snake.svg into dist/
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: th3adittya
          outputs: |
            dist/snake.svg

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/snake.svg
          git status
          git commit -m "chore: update snake svg" || echo "No changes to commit"
          git push origin HEAD:main
